################## BASE IMAGE ######################

FROM biocontainers/biocontainers:latest

################## INSTALLATION ######################

ENV ZIP=bowtie2-2.2.9-linux-x86_64.zip
ENV URL=https://github.com/BenLangmead/bowtie2/releases/download/v2.2.9/
ENV FOLDER=bowtie2-2.2.9
ENV DST=/home/biodocker/bin

RUN wget $URL/$ZIP -O $DST/$ZIP && \
    unzip $DST/$ZIP -d $DST && \
    rm $DST/$ZIP && \
    mv $DST/$FOLDER/* $DST && \
    rmdir $DST/$FOLDER

RUN conda install -c bioconda samtools
RUN conda install -c bioconda lofreq
RUN conda install -c bioconda bcftools

WORKDIR /data